language: python

services:
  - postgresql

env:
  global:
    - ON_TRAVIS=true
    - DJANGO_DEBUG=True
    - DJANGO_SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DEFAULT_DB_URL='postgis://postgres:@localhost:5432/test_db'

sudo: false
dist: bionic

python:
  - '3.6'

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.5

install:
  - pip install codecov
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db

script:
  - cd deployment
#  - make flake8
  - cd ../
  - python manage.py migrate
  - python manage.py collectstatic --noinput --verbosity 0
#  - coverage run manage.py test

after_success:
  - codecov

email:
 - zakki@kartoza.com