# Generated by Django 3.0.3 on 2020-04-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
