# Generated by Django 3.0.3 on 2020-04-29 04:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200429_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, help_text='Geometry of this grid', null=True, srid=4326)),
                ('population', models.IntegerField(default=300, help_text='Number of people in this grid')),
            ],
            options={
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
