# Generated by Django 3.0.3 on 2020-04-29 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_kmgrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmgrid',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, help_text='Geometry of this grid', null=True, srid=4326),
        ),
    ]
