# Generated by Django 3.0.3 on 2020-05-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_kmgridscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmgridscore',
            name='total_report',
            field=models.SmallIntegerField(default=0, help_text='The number of all report in the grid'),
        ),
    ]
