# Generated by Django 3.0.3 on 2020-05-05 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_kmgridscore_total_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='report',
            name='current',
            field=models.BooleanField(default=True, help_text='Flag to indicate current status.'),
        ),
        migrations.AddField(
            model_name='report',
            name='grid',
            field=models.ForeignKey(blank=True, default=None, help_text='Grid reference of the report', null=True, on_delete=django.db.models.deletion.CASCADE, to='report.KmGrid'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(help_text='Owner/user of this report', on_delete=django.db.models.deletion.CASCADE, to='report.User'),
        ),
    ]
